# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Chordxy\Github Clone\EassyReading\EassyReading.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.plainTextEdit_Eassy = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_Eassy.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_Eassy.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_Eassy.setFont(font)
        self.plainTextEdit_Eassy.setTabChangesFocus(True)
        self.plainTextEdit_Eassy.setObjectName("plainTextEdit_Eassy")
        self.gridLayout.addWidget(self.plainTextEdit_Eassy, 0, 1, 1, 1)
        self.plainTextEdit_KeyWords = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_KeyWords.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_KeyWords.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_KeyWords.setFont(font)
        self.plainTextEdit_KeyWords.setTabChangesFocus(True)
        self.plainTextEdit_KeyWords.setObjectName("plainTextEdit_KeyWords")
        self.gridLayout.addWidget(self.plainTextEdit_KeyWords, 7, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_Input = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.checkBox_Input.setFont(font)
        self.checkBox_Input.setObjectName("checkBox_Input")
        self.gridLayout_3.addWidget(self.checkBox_Input, 0, 0, 1, 1)
        self.checkBox_Proposal = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Proposal.setObjectName("checkBox_Proposal")
        self.gridLayout_3.addWidget(self.checkBox_Proposal, 0, 1, 1, 1)
        self.checkBox_Architecture = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Architecture.setObjectName("checkBox_Architecture")
        self.gridLayout_3.addWidget(self.checkBox_Architecture, 0, 2, 1, 1)
        self.checkBox_Module = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Module.setObjectName("checkBox_Module")
        self.gridLayout_3.addWidget(self.checkBox_Module, 0, 3, 1, 1)
        self.checkBox_Backbone = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Backbone.setObjectName("checkBox_Backbone")
        self.gridLayout_3.addWidget(self.checkBox_Backbone, 1, 0, 1, 1)
        self.checkBox_Convolution = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Convolution.setObjectName("checkBox_Convolution")
        self.gridLayout_3.addWidget(self.checkBox_Convolution, 1, 1, 1, 1)
        self.checkBox_Pooling = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Pooling.setObjectName("checkBox_Pooling")
        self.gridLayout_3.addWidget(self.checkBox_Pooling, 1, 2, 1, 1)
        self.checkBox_Classifier = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Classifier.setObjectName("checkBox_Classifier")
        self.gridLayout_3.addWidget(self.checkBox_Classifier, 1, 3, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 5, 1, 1, 1)
        self.label_Eassy = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_Eassy.setFont(font)
        self.label_Eassy.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_Eassy.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Eassy.setObjectName("label_Eassy")
        self.gridLayout.addWidget(self.label_Eassy, 0, 0, 1, 1)
        self.label_Innovation = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_Innovation.setFont(font)
        self.label_Innovation.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Innovation.setObjectName("label_Innovation")
        self.gridLayout.addWidget(self.label_Innovation, 5, 0, 1, 1)
        self.label_Comments = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_Comments.setFont(font)
        self.label_Comments.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Comments.setObjectName("label_Comments")
        self.gridLayout.addWidget(self.label_Comments, 8, 0, 1, 1)
        self.label_Base = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_Base.setFont(font)
        self.label_Base.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Base.setObjectName("label_Base")
        self.gridLayout.addWidget(self.label_Base, 4, 0, 1, 1)
        self.plainTextEdit_NetName = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_NetName.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_NetName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_NetName.setFont(font)
        self.plainTextEdit_NetName.setTabChangesFocus(True)
        self.plainTextEdit_NetName.setObjectName("plainTextEdit_NetName")
        self.gridLayout.addWidget(self.plainTextEdit_NetName, 3, 1, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox.sizePolicy().hasHeightForWidth())
        self.spinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox.setFont(font)
        self.spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox.setMinimum(1900)
        self.spinBox.setMaximum(2100)
        self.spinBox.setProperty("value", 2020)
        self.spinBox.setDisplayIntegerBase(10)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 2, 1, 1, 1)
        self.labelYear = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelYear.setFont(font)
        self.labelYear.setAlignment(QtCore.Qt.AlignCenter)
        self.labelYear.setObjectName("labelYear")
        self.gridLayout.addWidget(self.labelYear, 2, 0, 1, 1)
        self.plainTextEdit_Base = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_Base.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_Base.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_Base.setFont(font)
        self.plainTextEdit_Base.setTabChangesFocus(True)
        self.plainTextEdit_Base.setObjectName("plainTextEdit_Base")
        self.gridLayout.addWidget(self.plainTextEdit_Base, 4, 1, 1, 1)
        self.label_NetName = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_NetName.setFont(font)
        self.label_NetName.setAlignment(QtCore.Qt.AlignCenter)
        self.label_NetName.setObjectName("label_NetName")
        self.gridLayout.addWidget(self.label_NetName, 3, 0, 1, 1)
        self.label_Author = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_Author.setFont(font)
        self.label_Author.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Author.setObjectName("label_Author")
        self.gridLayout.addWidget(self.label_Author, 1, 0, 1, 1)
        self.label_KeyWords = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_KeyWords.setFont(font)
        self.label_KeyWords.setAlignment(QtCore.Qt.AlignCenter)
        self.label_KeyWords.setObjectName("label_KeyWords")
        self.gridLayout.addWidget(self.label_KeyWords, 7, 0, 1, 1)
        self.plainTextEdit_Author = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_Author.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_Author.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_Author.setFont(font)
        self.plainTextEdit_Author.setTabChangesFocus(True)
        self.plainTextEdit_Author.setObjectName("plainTextEdit_Author")
        self.gridLayout.addWidget(self.plainTextEdit_Author, 1, 1, 1, 1)
        self.plainTextEdit_Comments = QtWidgets.QPlainTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_Comments.setFont(font)
        self.plainTextEdit_Comments.setTabChangesFocus(True)
        self.plainTextEdit_Comments.setObjectName("plainTextEdit_Comments")
        self.gridLayout.addWidget(self.plainTextEdit_Comments, 8, 1, 1, 1)
        self.label_Recommend = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_Recommend.setFont(font)
        self.label_Recommend.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Recommend.setObjectName("label_Recommend")
        self.gridLayout.addWidget(self.label_Recommend, 6, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_star1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(35)
        sizePolicy.setVerticalStretch(35)
        sizePolicy.setHeightForWidth(self.pushButton_star1.sizePolicy().hasHeightForWidth())
        self.pushButton_star1.setSizePolicy(sizePolicy)
        self.pushButton_star1.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_star1.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_star1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_star1.setStyleSheet("border-image: url(:/Icons/Resources/gray_star_256px_1075532_easyicon.net.png);")
        self.pushButton_star1.setText("")
        self.pushButton_star1.setObjectName("pushButton_star1")
        self.horizontalLayout.addWidget(self.pushButton_star1)
        self.pushButton_star2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(35)
        sizePolicy.setVerticalStretch(35)
        sizePolicy.setHeightForWidth(self.pushButton_star2.sizePolicy().hasHeightForWidth())
        self.pushButton_star2.setSizePolicy(sizePolicy)
        self.pushButton_star2.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_star2.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_star2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_star2.setStyleSheet("border-image: url(:/Icons/Resources/gray_star_256px_1075532_easyicon.net.png);")
        self.pushButton_star2.setText("")
        self.pushButton_star2.setObjectName("pushButton_star2")
        self.horizontalLayout.addWidget(self.pushButton_star2)
        self.pushButton_star3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(35)
        sizePolicy.setVerticalStretch(35)
        sizePolicy.setHeightForWidth(self.pushButton_star3.sizePolicy().hasHeightForWidth())
        self.pushButton_star3.setSizePolicy(sizePolicy)
        self.pushButton_star3.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_star3.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_star3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_star3.setStyleSheet("border-image: url(:/Icons/Resources/gray_star_256px_1075532_easyicon.net.png);")
        self.pushButton_star3.setText("")
        self.pushButton_star3.setObjectName("pushButton_star3")
        self.horizontalLayout.addWidget(self.pushButton_star3)
        self.pushButton_star4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(35)
        sizePolicy.setVerticalStretch(35)
        sizePolicy.setHeightForWidth(self.pushButton_star4.sizePolicy().hasHeightForWidth())
        self.pushButton_star4.setSizePolicy(sizePolicy)
        self.pushButton_star4.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_star4.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_star4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_star4.setStyleSheet("border-image: url(:/Icons/Resources/gray_star_256px_1075532_easyicon.net.png);")
        self.pushButton_star4.setText("")
        self.pushButton_star4.setObjectName("pushButton_star4")
        self.horizontalLayout.addWidget(self.pushButton_star4)
        self.pushButton_star5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(35)
        sizePolicy.setVerticalStretch(35)
        sizePolicy.setHeightForWidth(self.pushButton_star5.sizePolicy().hasHeightForWidth())
        self.pushButton_star5.setSizePolicy(sizePolicy)
        self.pushButton_star5.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_star5.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_star5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_star5.setStyleSheet("border-image: url(:/Icons/Resources/gray_star_256px_1075532_easyicon.net.png);")
        self.pushButton_star5.setText("")
        self.pushButton_star5.setObjectName("pushButton_star5")
        self.horizontalLayout.addWidget(self.pushButton_star5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 6, 1, 1, 1)
        self.gridLayout.setRowStretch(0, 4)
        self.gridLayout.setRowStretch(1, 2)
        self.gridLayout.setRowStretch(2, 2)
        self.gridLayout.setRowStretch(3, 2)
        self.gridLayout.setRowStretch(4, 2)
        self.gridLayout.setRowStretch(5, 6)
        self.gridLayout.setRowStretch(6, 4)
        self.gridLayout.setRowStretch(7, 8)
        self.gridLayout.setRowStretch(8, 12)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.action_copy = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Functions/Resources/copy_256px_1113380_easyicon.net.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action_copy.setIcon(icon)
        self.action_copy.setObjectName("action_copy")
        self.action_clear = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Functions/Resources/delete_file_512px_1187316_easyicon.net.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action_clear.setIcon(icon1)
        self.action_clear.setObjectName("action_clear")
        self.action_loadin = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Functions/Resources/document_128px_1287920_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action_loadin.setIcon(icon2)
        self.action_loadin.setObjectName("action_loadin")
        self.action_top = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Functions/Resources/Thumbtack_pin_512px_1187300_easyicon.net.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action_top.setIcon(icon3)
        self.action_top.setObjectName("action_top")
        self.action_quit = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Functions/Resources/close_256px_1159854_easyicon.net.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action_quit.setIcon(icon4)
        self.action_quit.setObjectName("action_quit")
        self.action_open = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Functions/Resources/file_412px_1291720_easyicon.net.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action_open.setIcon(icon5)
        self.action_open.setObjectName("action_open")
        self.action_directory = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Functions/Resources/Path_512px_1128726_easyicon.net.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon6.addPixmap(QtGui.QPixmap(":/Functions/Resources/Path_512px_1128726_easyicon.net.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_directory.setIcon(icon6)
        self.action_directory.setObjectName("action_directory")
        self.action_I = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Functions/Resources/file_412.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_I.setIcon(icon7)
        self.action_I.setObjectName("action_I")
        self.toolBar.addAction(self.action_open)
        self.toolBar.addAction(self.action_I)
        self.toolBar.addAction(self.action_directory)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_copy)
        self.toolBar.addAction(self.action_clear)
        self.toolBar.addAction(self.action_loadin)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_top)
        self.toolBar.addAction(self.action_quit)

        self.retranslateUi(MainWindow)
        self.action_quit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.plainTextEdit_Eassy, self.plainTextEdit_Author)
        MainWindow.setTabOrder(self.plainTextEdit_Author, self.spinBox)
        MainWindow.setTabOrder(self.spinBox, self.plainTextEdit_NetName)
        MainWindow.setTabOrder(self.plainTextEdit_NetName, self.plainTextEdit_Base)
        MainWindow.setTabOrder(self.plainTextEdit_Base, self.plainTextEdit_KeyWords)
        MainWindow.setTabOrder(self.plainTextEdit_KeyWords, self.plainTextEdit_Comments)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "创新点"))
        self.checkBox_Input.setText(_translate("MainWindow", "Input"))
        self.checkBox_Proposal.setText(_translate("MainWindow", "Proposal"))
        self.checkBox_Architecture.setText(_translate("MainWindow", "Architecture"))
        self.checkBox_Module.setText(_translate("MainWindow", "Module"))
        self.checkBox_Backbone.setText(_translate("MainWindow", "Backbone"))
        self.checkBox_Convolution.setText(_translate("MainWindow", "Convolution"))
        self.checkBox_Pooling.setText(_translate("MainWindow", "Pooling"))
        self.checkBox_Classifier.setText(_translate("MainWindow", "Classifier"))
        self.label_Eassy.setText(_translate("MainWindow", "论文名"))
        self.label_Innovation.setText(_translate("MainWindow", "创新点"))
        self.label_Comments.setText(_translate("MainWindow", "简评"))
        self.label_Base.setText(_translate("MainWindow", "源模型"))
        self.labelYear.setText(_translate("MainWindow", "年份"))
        self.label_NetName.setText(_translate("MainWindow", "网络名"))
        self.label_Author.setText(_translate("MainWindow", "作者"))
        self.label_KeyWords.setText(_translate("MainWindow", "关键词"))
        self.label_Recommend.setText(_translate("MainWindow", "推荐度"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_copy.setText(_translate("MainWindow", "复制（W）"))
        self.action_copy.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.action_clear.setText(_translate("MainWindow", "清空（E）"))
        self.action_clear.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.action_loadin.setText(_translate("MainWindow", "读入（R）"))
        self.action_loadin.setToolTip(_translate("MainWindow", "读入（R）"))
        self.action_loadin.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.action_top.setText(_translate("MainWindow", "置顶（T）"))
        self.action_top.setToolTip(_translate("MainWindow", "置顶（T）"))
        self.action_top.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.action_quit.setText(_translate("MainWindow", "退出（Q）"))
        self.action_quit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.action_open.setText(_translate("MainWindow", "打开（F）"))
        self.action_open.setToolTip(_translate("MainWindow", "打开（F）"))
        self.action_open.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.action_directory.setText(_translate("MainWindow", "工作路径（D）"))
        self.action_directory.setToolTip(_translate("MainWindow", "工作路径（D）"))
        self.action_directory.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.action_I.setText(_translate("MainWindow", "取消搜索(I)"))
        self.action_I.setToolTip(_translate("MainWindow", "取消搜索(I)"))
        self.action_I.setShortcut(_translate("MainWindow", "Ctrl+I"))
import Resrouces_rc
