# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Chordxy\自写代码\EasyReading\EassyReading.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_Base = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_Base.setFont(font)
        self.label_Base.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Base.setObjectName("label_Base")
        self.gridLayout.addWidget(self.label_Base, 4, 0, 1, 1)
        self.label_Comments = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_Comments.setFont(font)
        self.label_Comments.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Comments.setObjectName("label_Comments")
        self.gridLayout.addWidget(self.label_Comments, 7, 0, 1, 1)
        self.plainTextEdit_Eassy = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_Eassy.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_Eassy.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_Eassy.setFont(font)
        self.plainTextEdit_Eassy.setTabChangesFocus(True)
        self.plainTextEdit_Eassy.setObjectName("plainTextEdit_Eassy")
        self.gridLayout.addWidget(self.plainTextEdit_Eassy, 0, 1, 1, 1)
        self.label_KeyWords = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_KeyWords.setFont(font)
        self.label_KeyWords.setAlignment(QtCore.Qt.AlignCenter)
        self.label_KeyWords.setObjectName("label_KeyWords")
        self.gridLayout.addWidget(self.label_KeyWords, 6, 0, 1, 1)
        self.plainTextEdit_Author = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_Author.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_Author.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_Author.setFont(font)
        self.plainTextEdit_Author.setTabChangesFocus(True)
        self.plainTextEdit_Author.setObjectName("plainTextEdit_Author")
        self.gridLayout.addWidget(self.plainTextEdit_Author, 1, 1, 1, 1)
        self.plainTextEdit_NetName = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_NetName.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_NetName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_NetName.setFont(font)
        self.plainTextEdit_NetName.setTabChangesFocus(True)
        self.plainTextEdit_NetName.setObjectName("plainTextEdit_NetName")
        self.gridLayout.addWidget(self.plainTextEdit_NetName, 3, 1, 1, 1)
        self.plainTextEdit_KeyWords = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_KeyWords.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_KeyWords.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_KeyWords.setFont(font)
        self.plainTextEdit_KeyWords.setTabChangesFocus(True)
        self.plainTextEdit_KeyWords.setObjectName("plainTextEdit_KeyWords")
        self.gridLayout.addWidget(self.plainTextEdit_KeyWords, 6, 1, 1, 1)
        self.label_Author = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_Author.setFont(font)
        self.label_Author.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Author.setObjectName("label_Author")
        self.gridLayout.addWidget(self.label_Author, 1, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox.sizePolicy().hasHeightForWidth())
        self.spinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox.setFont(font)
        self.spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox.setMinimum(1900)
        self.spinBox.setMaximum(2100)
        self.spinBox.setProperty("value", 2020)
        self.spinBox.setDisplayIntegerBase(10)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 2, 1, 1, 1)
        self.label_NetName = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_NetName.setFont(font)
        self.label_NetName.setAlignment(QtCore.Qt.AlignCenter)
        self.label_NetName.setObjectName("label_NetName")
        self.gridLayout.addWidget(self.label_NetName, 3, 0, 1, 1)
        self.plainTextEdit_Comments = QtWidgets.QPlainTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_Comments.setFont(font)
        self.plainTextEdit_Comments.setTabChangesFocus(True)
        self.plainTextEdit_Comments.setObjectName("plainTextEdit_Comments")
        self.gridLayout.addWidget(self.plainTextEdit_Comments, 7, 1, 1, 1)
        self.label_Eassy = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_Eassy.setFont(font)
        self.label_Eassy.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_Eassy.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Eassy.setObjectName("label_Eassy")
        self.gridLayout.addWidget(self.label_Eassy, 0, 0, 1, 1)
        self.labelYear = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelYear.setFont(font)
        self.labelYear.setAlignment(QtCore.Qt.AlignCenter)
        self.labelYear.setObjectName("labelYear")
        self.gridLayout.addWidget(self.labelYear, 2, 0, 1, 1)
        self.label_Innovation = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_Innovation.setFont(font)
        self.label_Innovation.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Innovation.setObjectName("label_Innovation")
        self.gridLayout.addWidget(self.label_Innovation, 5, 0, 1, 1)
        self.plainTextEdit_Base = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_Base.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_Base.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_Base.setFont(font)
        self.plainTextEdit_Base.setTabChangesFocus(True)
        self.plainTextEdit_Base.setObjectName("plainTextEdit_Base")
        self.gridLayout.addWidget(self.plainTextEdit_Base, 4, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_Input = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.checkBox_Input.setFont(font)
        self.checkBox_Input.setObjectName("checkBox_Input")
        self.gridLayout_3.addWidget(self.checkBox_Input, 0, 0, 1, 1)
        self.checkBox_Proposal = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Proposal.setObjectName("checkBox_Proposal")
        self.gridLayout_3.addWidget(self.checkBox_Proposal, 0, 1, 1, 1)
        self.checkBox_Architecture = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Architecture.setObjectName("checkBox_Architecture")
        self.gridLayout_3.addWidget(self.checkBox_Architecture, 0, 2, 1, 1)
        self.checkBox_Module = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Module.setObjectName("checkBox_Module")
        self.gridLayout_3.addWidget(self.checkBox_Module, 0, 3, 1, 1)
        self.checkBox_Backbone = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Backbone.setObjectName("checkBox_Backbone")
        self.gridLayout_3.addWidget(self.checkBox_Backbone, 1, 0, 1, 1)
        self.checkBox_Convolution = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Convolution.setObjectName("checkBox_Convolution")
        self.gridLayout_3.addWidget(self.checkBox_Convolution, 1, 1, 1, 1)
        self.checkBox_Pooling = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Pooling.setObjectName("checkBox_Pooling")
        self.gridLayout_3.addWidget(self.checkBox_Pooling, 1, 2, 1, 1)
        self.checkBox_Classifier = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Classifier.setObjectName("checkBox_Classifier")
        self.gridLayout_3.addWidget(self.checkBox_Classifier, 1, 3, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 5, 1, 1, 1)
        self.gridLayout.setRowStretch(0, 4)
        self.gridLayout.setRowStretch(1, 2)
        self.gridLayout.setRowStretch(2, 2)
        self.gridLayout.setRowStretch(3, 2)
        self.gridLayout.setRowStretch(4, 2)
        self.gridLayout.setRowStretch(5, 6)
        self.gridLayout.setRowStretch(6, 8)
        self.gridLayout.setRowStretch(7, 12)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 6, 1, 1)
        self.pushButton_top = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_top.setObjectName("pushButton_top")
        self.gridLayout_2.addWidget(self.pushButton_top, 0, 1, 1, 1)
        self.pushButton_quit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_quit.setObjectName("pushButton_quit")
        self.gridLayout_2.addWidget(self.pushButton_quit, 0, 9, 1, 1)
        self.pushButton_copy = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_copy.setObjectName("pushButton_copy")
        self.gridLayout_2.addWidget(self.pushButton_copy, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 10, 1, 1)
        self.pushButton_Load = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Load.setObjectName("pushButton_Load")
        self.gridLayout_2.addWidget(self.pushButton_Load, 0, 7, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 8, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 0, 4, 1, 1)
        self.pushButton_clear = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.gridLayout_2.addWidget(self.pushButton_clear, 0, 5, 1, 1)
        self.pushButton_PasteEassy = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_PasteEassy.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_PasteEassy.setObjectName("pushButton_PasteEassy")
        self.gridLayout_2.addWidget(self.pushButton_PasteEassy, 1, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 1, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 1, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 1, 4, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 1, 6, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem10, 1, 8, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem11, 1, 10, 1, 1)
        self.pushButton_PasteAuthor = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_PasteAuthor.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_PasteAuthor.setObjectName("pushButton_PasteAuthor")
        self.gridLayout_2.addWidget(self.pushButton_PasteAuthor, 1, 3, 1, 1)
        self.pushButton_PasteKeywords = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_PasteKeywords.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_PasteKeywords.setObjectName("pushButton_PasteKeywords")
        self.gridLayout_2.addWidget(self.pushButton_PasteKeywords, 1, 7, 1, 1)
        self.pushButton_PasteComments = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_PasteComments.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_PasteComments.setObjectName("pushButton_PasteComments")
        self.gridLayout_2.addWidget(self.pushButton_PasteComments, 1, 9, 1, 1)
        self.pushButton_PasteModel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_PasteModel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_PasteModel.setObjectName("pushButton_PasteModel")
        self.gridLayout_2.addWidget(self.pushButton_PasteModel, 1, 5, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.plainTextEdit_Eassy, self.plainTextEdit_Author)
        MainWindow.setTabOrder(self.plainTextEdit_Author, self.spinBox)
        MainWindow.setTabOrder(self.spinBox, self.plainTextEdit_NetName)
        MainWindow.setTabOrder(self.plainTextEdit_NetName, self.plainTextEdit_Base)
        MainWindow.setTabOrder(self.plainTextEdit_Base, self.plainTextEdit_KeyWords)
        MainWindow.setTabOrder(self.plainTextEdit_KeyWords, self.plainTextEdit_Comments)
        MainWindow.setTabOrder(self.plainTextEdit_Comments, self.pushButton_top)
        MainWindow.setTabOrder(self.pushButton_top, self.pushButton_copy)
        MainWindow.setTabOrder(self.pushButton_copy, self.pushButton_clear)
        MainWindow.setTabOrder(self.pushButton_clear, self.pushButton_Load)
        MainWindow.setTabOrder(self.pushButton_Load, self.pushButton_quit)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Base.setText(_translate("MainWindow", "源模型"))
        self.label_Comments.setText(_translate("MainWindow", "简评"))
        self.label_KeyWords.setText(_translate("MainWindow", "关键词"))
        self.label_Author.setText(_translate("MainWindow", "作者"))
        self.label_NetName.setText(_translate("MainWindow", "网络名"))
        self.label_Eassy.setText(_translate("MainWindow", "论文名"))
        self.labelYear.setText(_translate("MainWindow", "年份"))
        self.label_Innovation.setText(_translate("MainWindow", "创新点"))
        self.groupBox.setTitle(_translate("MainWindow", "创新点"))
        self.checkBox_Input.setText(_translate("MainWindow", "Input"))
        self.checkBox_Proposal.setText(_translate("MainWindow", "Proposal"))
        self.checkBox_Architecture.setText(_translate("MainWindow", "Architecture"))
        self.checkBox_Module.setText(_translate("MainWindow", "Module"))
        self.checkBox_Backbone.setText(_translate("MainWindow", "Backbone"))
        self.checkBox_Convolution.setText(_translate("MainWindow", "Convolution"))
        self.checkBox_Pooling.setText(_translate("MainWindow", "Pooling"))
        self.checkBox_Classifier.setText(_translate("MainWindow", "Classifier"))
        self.pushButton_top.setText(_translate("MainWindow", "置顶(R)"))
        self.pushButton_top.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.pushButton_quit.setText(_translate("MainWindow", "退出(Q)"))
        self.pushButton_quit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.pushButton_copy.setText(_translate("MainWindow", "复制(W)"))
        self.pushButton_copy.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.pushButton_Load.setText(_translate("MainWindow", "读入(T)"))
        self.pushButton_Load.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.pushButton_clear.setText(_translate("MainWindow", "清空(E)"))
        self.pushButton_clear.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.pushButton_PasteEassy.setText(_translate("MainWindow", "论文名(1)"))
        self.pushButton_PasteEassy.setShortcut(_translate("MainWindow", "Ctrl+1"))
        self.pushButton_PasteAuthor.setText(_translate("MainWindow", "作者(2)"))
        self.pushButton_PasteAuthor.setShortcut(_translate("MainWindow", "Ctrl+2"))
        self.pushButton_PasteKeywords.setText(_translate("MainWindow", "关键词(4)"))
        self.pushButton_PasteKeywords.setShortcut(_translate("MainWindow", "Ctrl+4"))
        self.pushButton_PasteComments.setText(_translate("MainWindow", "简评(5)"))
        self.pushButton_PasteComments.setShortcut(_translate("MainWindow", "Ctrl+5"))
        self.pushButton_PasteModel.setText(_translate("MainWindow", "源模型(3)"))
        self.pushButton_PasteModel.setShortcut(_translate("MainWindow", "Ctrl+3"))
import Resrouces_rc
